#!/usr/bin/env python3
"""Assemble the self-contained pages from templates + data/john-data.json.

  index.html        index.template.html  + scripts/app.js
  city3d.html       city3d.template.html + scripts/app3d.js          (canvas renderer)
  city3d-three.html city3d.template.html + build/city3d-three.bundle.js (Three.js)

The Three.js page needs `npm run bundle` first; if the bundle is missing it is
skipped with a warning so the pure-python build still works.
"""
import datetime
import json
import os
import subprocess
import sys

ALT_2D = '<a href="index.html">2D map ↩</a>'


def build_stamp():
    """A visible marker of which commit a page was built from, so a refresh can be
    told apart from a stale cache. The hash is HEAD at build time — the built HTML
    is committed after, so it names the source state, not the commit holding it."""
    def git(*args):
        try:
            return subprocess.run(["git", *args], capture_output=True, text=True,
                                  check=True).stdout.strip()
        except Exception:
            return ""
    sha = git("rev-parse", "--short", "HEAD")
    built = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M")
    label = f"build {built}Z" + (f" · {sha}" if sha else "")
    if not sha:
        return f'<span class="build">{label}</span>'
    url = f"https://github.com/recklessnode/gospel-of-john-city/commit/{sha}"
    return (f'<a class="build" href="{url}" target="_blank" rel="noopener" '
            f'title="the commit this page was built from">{label}</a>')


STAMP = build_stamp()


def js_json(obj):
    """Compact JSON safe to inline in a <script> block: '</' cannot end the script early."""
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def assemble(template, app, data, out, subtitle, alt_link, chiasm_iife=None, ways=None):
    html = template.replace("/*__DATA__*/;", json.dumps(data, ensure_ascii=False) + ";")
    # The chiasm corpus rides in front of the app code as window.JOHN_CHIASMS —
    # src/chiasm-ui.js picks it up lazily, so no page needs an init call. The two
    # script-tag pages also get the module itself as an IIFE (window.ChiasmUI);
    # city3d-three.html already has it inside its bundle via src/main.js.
    prefix = ""
    if chiasms is not None:
        prefix += ("window.JOHN_CHIASMS = "
                   + json.dumps(chiasms, ensure_ascii=False, separators=(",", ":")) + ";\n")
    if chiasm_iife:
        prefix += chiasm_iife + "\n"
    # Theme ways (PaulDz's issue-#2 lists, measured and banded) ride in the 2D page only
    # until slice 2 gives the 3D views a consumer. JOHN_WAYTHEMES, not JOHN_THEMES, so it
    # cannot be confused with JOHN.themes — the seven narrative colour categories.
    if ways is not None:
        prefix += "window.JOHN_WAYTHEMES = " + js_json(ways[0]) + ";\n"
        prefix += "window.JOHN_WAYS = " + js_json(ways[1]) + ";\n"
    html = html.replace("/*__APP__*/", prefix + app)
    html = html.replace("<!--__SUBTITLE__-->", subtitle)
    html = html.replace("<!--__ALT__-->", alt_link)
    html = html.replace("<!--__BUILD__-->", STAMP)
    with open(out, "w") as f:
        f.write(html)
    # len(html) counts characters; the page is UTF-8, so measure what is actually written
    print(f"{out} written ({len(html.encode('utf-8')):,} bytes)")


with open("data/john-data.json") as f:
    data = json.load(f)

# The chiasm structure (data/chiasms.json, generated by scripts/build_chiasms.py
# from PaulDz's transcription of Malina & Rohrbaugh). Missing is survivable —
# same rule as the missing 3-D bundle — the pages just show no chiasms.
CHIASMS = "data/chiasms.json"
if os.path.exists(CHIASMS):
    with open(CHIASMS) as f:
        chiasms = json.load(f)
else:
    chiasms = None
    print(f"! {CHIASMS} missing — run `python3 scripts/build_chiasms.py`; pages built without chiasms")

# Theme ways: both are committed sources, so a missing file is a broken checkout, not a
# degraded build — refuse rather than ship a page that silently has no ways.
WAYS_SRC = ("data/themes.json", "data/way-types.json")
for p in WAYS_SRC:
    if not os.path.exists(p):
        sys.exit(f"✗ {p} missing — refusing to build (it is a committed source)")
with open(WAYS_SRC[0], encoding="utf-8") as f:
    waythemes = json.load(f)
with open(WAYS_SRC[1], encoding="utf-8") as f:
    waytypes = json.load(f)

CHIASM_IIFE = "build/chiasm-ui.iife.js"
if os.path.exists(CHIASM_IIFE):
    with open(CHIASM_IIFE) as f:
        chiasm_ui = f.read()
else:
    chiasm_ui = None
    print(f"! {CHIASM_IIFE} missing — run `npm run bundle`; index.html/city3d.html built without the chiasm reader")

with open("index.template.html") as f:
    tpl2d = f.read()
with open("scripts/app.js") as f:
    assemble(tpl2d, f.read(), data, "index.html", "", "", chiasm_ui, ways=(waythemes, waytypes))

with open("city3d.template.html") as f:
    tpl3d = f.read()

with open("scripts/app3d.js") as f:
    assemble(tpl3d, f.read(), data, "city3d.html",
             "3D · classic canvas renderer",
             '<a href="city3d-three.html">ancient city ↩</a>', chiasm_ui)

BUNDLE = "build/city3d-three.bundle.js"
if os.path.exists(BUNDLE):
    with open(BUNDLE) as f:
        assemble(tpl3d, f.read(), data, "city3d-three.html",
                 "3D · ancient city · building height = Greek word count",
                 '<a href="city3d.html">classic 3D ↩</a>')
else:
    print(f"! {BUNDLE} missing — run `npm run bundle` to build city3d-three.html")
