/* chiasm-ui.js — the chiasm reader shared by all three renderers.
 *
 * Source of truth: data/chiasms.json, generated by scripts/build_chiasms.py from
 * PaulDz's transcription of Malina & Rohrbaugh, "Social-Science Commentary on the
 * Gospel of John" (Fortress Press 1998), appendix.
 *
 * Invariant 5 applies with full force here: everything on screen comes out of that
 * file. Nothing is invented, nothing is regularised. Irregular chiasms (missing
 * centres, doubled rungs, A A′ B C C′) are rendered exactly as irregular as they
 * are, and a block the source says nothing about renders nothing at all.
 *
 * Plain ES module, no imports, no DOM at load time: esbuild emits it twice — once
 * inside the Three.js bundle (imported by src/main.js) and once as an IIFE under
 * window.ChiasmUI for the two script-tag pages.
 */

/* ---------- data ---------- */

let DATA = null;

/** Optional override — tests and non-browser use. Consumers otherwise need no init. */
export function setData(d) { DATA = d; }

function data() { return DATA ?? globalThis.JOHN_CHIASMS; }

let cacheSrc, cacheUnits, cacheChiasms;
function idx() {
  const D = data();
  if (D !== cacheSrc) {
    cacheSrc = D;
    cacheUnits = new Map();
    cacheChiasms = new Map();
    if (D && Array.isArray(D.units)) {
      for (const u of D.units) {
        cacheUnits.set(u.id, u);
        for (const c of u.chiasms || []) cacheChiasms.set(c.id, { unit: u, chiasm: c });
      }
    }
  }
  return { D: cacheSrc, units: cacheUnits, chiasms: cacheChiasms };
}

/** hoodId -> unitId currently expanded ("" = the reader collapsed them all).
 *  Module scope on purpose: every openHood() rebuilds the panel from scratch. */
const openUnit = new Map();

/** hoodId -> arc unitId currently expanded. Arcs are wide-span context and get
 *  their own slot: reading the context must never close the block's own chiasm. */
const openArc = new Map();

/* ---------- small helpers ---------- */

const esc = s => String(s == null ? "" : s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const escRe = s => String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const muted = s => `<span style="color:var(--muted)">${esc(s)}</span>`;

/** A unit with a ladder worth expanding: a chiasm, or the marker table of an arc. */
function isLadder(u) { return (u.chiasms && u.chiasms.length > 0) || u.kind === "markerTable"; }

/** "4:7" + "4:14b" -> "4:7–14b". Only ever narrows what the source already says. */
function refSpan(u) {
  const refs = (u.rows || []).filter(r => r.ref).map(r => r.ref);
  if (!refs.length) return u.ref || "";
  const first = refs[0], last = refs[refs.length - 1];
  const start = first.split(/[–-]/)[0];
  const parts = last.split(/[–-]/);
  let end = parts[parts.length - 1];
  const ch = s => (s.indexOf(":") >= 0 ? s.slice(0, s.indexOf(":")) : null);
  const sch = ch(start), ech = ch(end);
  if (sch && ech && sch === ech) end = end.slice(end.indexOf(":") + 1);
  if (!end || start === end || start === sch + ":" + end) return start;
  return start + "–" + end;
}

/** Split the source's own label ("Theme 1 Water", "Marker V: … 8:20") into
 *  tag / title / reference without rewording any of it. `fromRows` asks for the
 *  span the rungs actually cover, which is what a ladder should be titled with. */
function headOf(u, fromRows) {
  const l = u.label;
  if (l) {
    let rest = l.text || "", tag = "";
    if (l.kind && rest.indexOf(l.kind) === 0) {
      tag = l.kind;
      rest = rest.slice(l.kind.length);
      // The source numbers some labels (Theme 1, Marker V). l.n says whether it
      // did, which keeps a verse reference from being mistaken for a number.
      const m = l.n != null ? rest.match(/^[:\s]*([IVXLC]+|\d+)(?=\s|$|:(?!\d))/) : null;
      if (m) { tag += " " + m[1]; rest = rest.slice(m[0].length); }
    }
    rest = rest.replace(/^[:\s]+/, "");
    const ref = l.ref || "";
    if (ref) rest = rest.replace(new RegExp("\\(?" + escRe(ref) + "\\)?"), " ");
    return {
      tag: tag,
      title: rest.replace(/\s+/g, " ").trim(),
      ref: (fromRows ? refSpan(u) : "") || ref || refSpan(u)
    };
  }
  const h = u.head || {};
  return { tag: h.sectionTag || "", title: h.title || "", ref: refSpan(u) };
}

/* ---------- the mirror ---------- */

/* Depth = how far into the fold a rung sits: the position of its base letter in
 * the order the bases first appear. A B C D C′ B′ A′ steps 0 1 2 3 2 1 0, so the
 * ladder draws the fold itself. An irregular pattern draws its irregularity. */
function depthMap(u, c) {
  const seen = new Map(), out = new Map();
  for (const i of c.rows) {
    const r = u.rows[i];
    const b = r.base || r.tag || "";
    if (!seen.has(b)) seen.set(b, seen.size);
  }
  for (const i of c.rows) {
    const r = u.rows[i];
    out.set(i, Math.min(seen.get(r.base || r.tag || "") || 0, 6));
  }
  return out;
}

const blankMeta = () =>
  ({ depth: 0, chi: false, centre: false, top: false, chip: false, edge: false, kind: null, bases: [] });

/* A derived centre is not the same claim as a marked one, and a nested
 * sub-chiasm's centre is not the block's centre. Both distinctions live in the
 * data (centre.kind, chiasm.parentRow) and both are carried through to the row
 * so the CSS can mark them differently instead of one gold box for all six. */
const CENTRE_NOTE = {
  band: "Centre inferred from the fold; the source marks none.",
  none: "No centre is marked in the source for this pattern.",
};

/** Per-row render facts, gathered from every chiasm the unit carries. */
function rowMeta(u) {
  const meta = new Map();
  const notes = new Map(); // row index -> notes printed after that row
  const get = i => {
    let m = meta.get(i);
    if (!m) { m = blankMeta(); meta.set(i, m); }
    return m;
  };
  const note = (i, text) => {
    const list = notes.get(i);
    if (list) { if (list.indexOf(text) < 0) list.push(text); } else notes.set(i, [text]);
  };
  for (const c of u.chiasms || []) {
    const top = c.parentRow == null;
    const d = depthMap(u, c);
    for (const i of c.rows) {
      const m = get(i);
      m.chi = true;
      m.depth = Math.max(m.depth, d.get(i) || 0);
      // Namespaced per chiasm: a bare letter would pair "a" at 20:3 with the "a"
      // of three unrelated sub-chiasms further down the same ladder.
      const b = u.rows[i] && u.rows[i].base;
      if (b) m.bases.push(c.id + "|" + b);
    }
    const ce = c.centre || { kind: "none", rows: [], pair: null, enclosed: [] };
    // The chip labels the centre once. A mirrored pair (D D′) wears it twice
    // because both rows are the centre; a group of four does not, or half the
    // ladder ends up shouting "centre".
    const mark = (i, k, n) => {
      const m = get(i);
      m.centre = true;
      if (top) {
        m.top = true;
        if (ce.kind !== "band" && (n <= 2 || k === 0)) m.chip = true;
      }
      if (m.kind == null || top) m.kind = ce.kind;
    };
    const markAll = list => list.forEach((i, k) => mark(i, k, list.length));
    if (ce.kind === "enclosed") {
      markAll(ce.enclosed || []);
      for (const i of ce.pair || []) get(i).edge = true;
    } else if (ce.kind === "none") {
      const last = c.rows.length ? c.rows[c.rows.length - 1] : -1;
      note(last, CENTRE_NOTE.none);
    } else {
      markAll(ce.rows || []);
      // footnote the whole pattern, not the inferred row, so it reads as a
      // caveat on the chiasm rather than a caption interrupting the ladder
      if (ce.kind === "band" && c.rows.length)
        note(c.rows[c.rows.length - 1], CENTRE_NOTE.band);
    }
  }
  return { meta, notes };
}

function rung(u, r, m) {
  const cls = ["rung"];
  if (!m.chi) cls.push("plain");
  if (m.centre) cls.push("center", m.top ? "center-top" : "center-sub");
  if (m.edge) cls.push("center-edge");
  if (r.level) cls.push("lvl" + Math.min(r.level, 2));
  const pad = 18 * (r.level || 0) + 14 * m.depth;
  const style = pad ? ` style="margin-left:${pad}px"` : "";
  let tag = r.tag || "";
  if (m.centre) tag = tag ? "◈ " + tag : "◈";
  const base = m.bases.length
    ? ` data-chi-base="${esc(m.bases.join(" "))}" tabindex="0" role="button"` : "";
  const kind = m.centre && m.kind ? ` data-chi-centre="${esc(m.kind)}"` : "";
  const body = (r.ref ? esc(r.ref) + " " : "") + esc(r.text || "");
  // One chip per ladder-level centre, and never on a centre the algorithm only
  // inferred (kind "band" carries the note above instead).
  const chip = m.chip ? `<span class="chi-centre-chip">centre</span>` : "";
  return `<div class="${cls.join(" ")}" data-chi-row="${r.i}"${base}${kind}${style}>` +
    `<span class="tag">${esc(tag)}</span><span class="chi-text">${body}</span>${chip}</div>`;
}

function ladder(u, id) {
  const { meta, notes } = rowMeta(u);
  let out = "";
  if (u.note) out += `<div class="note">${esc(u.note)}</div>`;
  const flush = i => {
    for (const t of notes.get(i) || []) out += `<div class="note">${esc(t)}</div>`;
  };
  for (const r of u.rows || []) {
    if (r.type === "text" && u.note && r.text === u.note) continue; // already printed above
    if (r.type === "subtitle" && !r.tag) {
      out += `<div class="rung plain"><span class="tag"></span><span class="chi-text">${muted(r.text)}</span></div>`;
    } else {
      out += rung(u, r, meta.get(r.i) || blankMeta());
    }
    flush(r.i);
  }
  flush(-1);
  return `<div class="ladder"${id ? ` id="${esc(id)}"` : ""}>${out}</div>`;
}

/* ---------- units ---------- */

/** The top-level pattern(s); nested sub-chiasms show themselves in the ladder. */
function patternOf(u) {
  return (u.chiasms || []).filter(c => c.parentRow == null).map(c => c.pattern)
    .filter(Boolean).join("  ·  ");
}

function renderArc(u, open) {
  const h = u.head || {};
  const n = (u.rows || []).filter(r => r.type === "roman" || r.type === "rung").length;
  const label = `${h.ref || u.ref || ""} ${h.title || ""}`.trim() +
    (n ? ` — ${n} marker${n === 1 ? "" : "s"}` : "");
  const lid = "ladder-" + u.id;
  return `<div class="chi-unit${open ? "" : " collapsed"} chi-arc-unit" data-chi-unit="${esc(u.id)}">` +
    `<button type="button" class="chi-arc" data-chi-open="${esc(u.id)}"` +
    ` aria-expanded="${open ? "true" : "false"}" aria-controls="${esc(lid)}">` +
    `<span class="chi-chev">▸</span><span>${esc(label)}</span></button>` +
    ladder(u, lid) + `</div>`;
}

function renderUnit(u, open) {
  const h = headOf(u, true);
  const pat = patternOf(u);
  const lid = "ladder-" + u.id;
  const head = `<button type="button" class="chi-head" data-chi-toggle="${esc(u.id)}"` +
    ` aria-expanded="${open ? "true" : "false"}" aria-controls="${esc(lid)}">` +
    `<span class="chi-chev">▸</span>` +
    (h.tag ? `<span class="tag">${esc(h.tag)}</span>` : "") +
    `<span class="chi-title" title="${esc(h.title)}">${esc(h.title)}${h.title && h.ref ? " " : ""}${h.ref ? muted("· " + h.ref) : ""}</span>` +
    (pat ? `<span class="chi-pat" title="${esc(pat)}">${esc(pat)}</span>` : "") +
    `</button>`;
  return `<div class="chi-unit${open ? "" : " collapsed"}" data-chi-unit="${esc(u.id)}">` +
    head + ladder(u, lid) + `</div>`;
}

/* ---------- the section-level chiasm ---------- */

/* Sections IX (13:1–17:26) and X (18:1–19:42) are themselves chiasms in the
 * source, with whole blocks as rungs. Without this the block is silent about
 * its own place in the fold — and 19:38–42, whose only source content IS its
 * A′ rung, showed nothing at all. */
function sectionRungOf(hoodId) {
  const D = data();
  const e = D && D.index && D.index.byHood ? D.index.byHood[hoodId] : null;
  const sr = e && e.sectionRung;
  if (!sr) return null;
  const sec = (D.sections || []).filter(s => s.id === sr.section)[0];
  if (!sec || !sec.chiasm) return null;
  const r = (sec.chiasm.rungs || []).filter(x => x.hood === hoodId)[0];
  if (!r) return null;
  return { sec, rung: r, isCentre: !!sr.isCentre };
}

/** `titleShown` = the block already prints this rung's title under it (its own
 *  chiasm carries the same source heading), so the rung line drops it rather
 *  than saying the same thing twice. */
function renderSectionRung(s, titleShown) {
  const tag = (s.isCentre ? "◈ " : "") + (s.rung.tag || "");
  const where = `${s.sec.roman}. ${s.sec.title}${s.sec.ref ? " · " + s.sec.ref : ""}`;
  const line = titleShown ? ""
    : `<span class="chi-sec-line">${s.rung.ref ? esc(s.rung.ref) + " " : ""}${esc(s.rung.text || "")}</span>`;
  return `<div class="chi-sec${s.isCentre ? " is-centre" : ""}">` +
    `<span class="tag">${esc(tag)}</span>` +
    `<span class="chi-text">` + line +
      `<span class="chi-sec-where">${s.isCentre ? "centre of " : "rung of "}${esc(where)} · ${esc(s.sec.chiasm.pattern)}</span>` +
    `</span>` +
    (s.isCentre ? `<span class="chi-centre-chip">centre</span>` : "") +
    `</div>`;
}

/** Transitions, introductions, addenda, conclusions, markers: the unchiasmed
 *  verses that the source hangs on the front or the back of a block. */
function renderFore(u) {
  const h = headOf(u);
  const line = esc(h.tag) + (h.title ? ": " + esc(h.title) : "") + (h.ref ? " " + muted("· " + h.ref) : "");
  let out = `<div class="detail-item chi-fore" data-chi-unit="${esc(u.id)}"><span>${line}</span></div>`;
  if (u.rows && u.rows.length) out += ladder(u);
  return out;
}

/* ---------- public surface ---------- */

export function hasChiasms(hoodId) {
  const D = data();
  const e = D && D.index && D.index.byHood ? D.index.byHood[hoodId] : null;
  if (!e) return false;
  return (e.units && e.units.length > 0) || (e.arcs && e.arcs.length > 0) || !!e.sectionRung;
}

/** The centre of one chiasm — read-only, for future map badges. */
export function centreOf(chiasmId) {
  const e = idx().chiasms.get(chiasmId);
  if (!e) return null;
  const c = e.chiasm.centre || { kind: "none", rows: [] };
  const rows = c.kind === "enclosed" ? (c.enclosed || []) : (c.rows || []);
  return { kind: c.kind, rows: rows.slice() };
}

export function renderHood(hoodId, opts) {
  opts = opts || {};
  const D = data();
  const e = D && D.index && D.index.byHood ? D.index.byHood[hoodId] : null;
  if (!e) return "";
  const { units } = idx();
  const arcs = (e.arcs || []).map(id => units.get(id)).filter(Boolean);
  const own = (e.units || []).map(id => units.get(id)).filter(Boolean);
  const sec = sectionRungOf(hoodId);
  if (!arcs.length && !own.length && !sec) return "";

  const ladders = own.filter(isLadder);
  let open = openUnit.has(hoodId) ? openUnit.get(hoodId) : null;
  if (opts.open != null) open = opts.open;
  // Land on a live chiasm, centre lit. The picker is still there for the rest —
  // a block of collapsed grey rows hides the one thing the reader came for.
  if (open === null) open = ladders.length ? ladders[0].id : "";
  // Arcs are wide-span context on their own latch, so opening one never shuts
  // the block's own chiasm.
  const openA = opts.openArc != null ? opts.openArc : (openArc.get(hoodId) || "");

  const secTitleShown = !!sec &&
    own.some(u => isLadder(u) && headOf(u, true).title === (sec.rung.text || ""));
  let body = sec ? renderSectionRung(sec, secTitleShown) : "", last = "";
  for (const u of arcs) {
    body += renderArc(u, u.id === openA);
    const ah = u.head || {};
    last = ((ah.ref || u.ref || "") + " " + (ah.title || "")).trim(); // don't repeat it below
  }

  // The source sometimes gathers several units under one heading (a group, or a
  // shared pericope head). Print that heading once, where it changes.
  const heads = new Set(own.map(u => (u.head ? u.head.ref + "|" + u.head.title : "")));
  for (const u of own) {
    const g = u.head && u.head.group ? u.head.group : (heads.size > 1 ? u.head : null);
    const divider = g ? ((g.ref || "") + " " + (g.title || "")).trim() : "";
    if (divider && divider !== last) {
      body += `<div class="chi-group">${esc(divider)}</div>`;
      last = divider;
    }
    body += isLadder(u) ? renderUnit(u, u.id === open) : renderFore(u);
  }

  const H = opts.headingLevel || "h3";
  // Only claim chiasms when the source gives this block one of its own. A block
  // whose sole content is a shared arc or a section rung is structure, not a chiasm.
  const hasOwn = own.some(u => (u.chiasms || []).length > 0);
  const title = hasOwn ? "Chiasms in this block" : "Structure in this block";
  return `<${H}>${title}</${H}><div class="chiasm-block" data-chiasm-hood="${esc(hoodId)}">${body}</div>`;
}

/* ---------- interaction ---------- */

const bound = new WeakMap(); // root element -> latest opts (panels are re-used)

function closest(el, sel) {
  while (el && el.nodeType === 1) {
    if (el.matches && el.matches(sel)) return el;
    el = el.parentElement;
  }
  return null;
}

function rungsOf(ladderEl) {
  return ladderEl ? Array.prototype.slice.call(ladderEl.querySelectorAll(".rung")) : [];
}

/** The chiasms a rung belongs to, as "<chiasmId>|<base>" tokens. */
function chiTokens(el) {
  const a = el.getAttribute("data-chi-base");
  return a ? a.split(" ") : [];
}

/** Light up a rung and its mirror partner — the pairing made literal. The token
 *  carries the owning chiasm, so the pairing stops at that chiasm's edge. */
function highlight(ladderEl, token) {
  for (const r of rungsOf(ladderEl)) {
    const on = !!token && chiTokens(r).indexOf(token) >= 0;
    if (on) r.classList.add("current");
    else r.classList.remove("current");
  }
}

function setExpanded(unitEl, open) {
  const head = unitEl.querySelector("[data-chi-toggle],[data-chi-open]");
  if (head) head.setAttribute("aria-expanded", open ? "true" : "false");
}

function onClick(root, ev) {
  const opts = bound.get(root) || {};
  const block = closest(ev.target, ".chiasm-block");
  if (!block) return;

  const toggle = closest(ev.target, "[data-chi-toggle],[data-chi-open]");
  if (toggle) {
    ev.stopPropagation();
    const id = toggle.getAttribute("data-chi-toggle") || toggle.getAttribute("data-chi-open");
    const hoodId = block.getAttribute("data-chiasm-hood");
    const unit = idx().units.get(id);
    const home = unit && unit.hood;
    if (home && home !== hoodId && typeof opts.onOpenHood === "function") {
      openUnit.set(home, id);
      opts.onOpenHood(home);
      return;
    }
    const target = closest(toggle, ".chi-unit");
    const isArc = !!target && target.classList.contains("chi-arc-unit");
    const wasOpen = target && !target.classList.contains("collapsed");
    // Arcs and the block's own chiasms are two independent accordions.
    const sel = isArc ? ".chi-unit.chi-arc-unit" : ".chi-unit:not(.chi-arc-unit)";
    for (const u of block.querySelectorAll(sel)) { u.classList.add("collapsed"); setExpanded(u, false); }
    if (target && !wasOpen) { target.classList.remove("collapsed"); setExpanded(target, true); }
    (isArc ? openArc : openUnit).set(hoodId, wasOpen ? "" : id);
    return;
  }

  const r = closest(ev.target, ".rung[data-chi-base]");
  if (r) {
    ev.stopPropagation();
    const ladderEl = closest(r, ".ladder");
    const token = chiTokens(r)[0];
    if (!ladderEl || !token) return;
    if (ladderEl.getAttribute("data-chi-pin") === token) {
      ladderEl.removeAttribute("data-chi-pin");
      highlight(ladderEl, null);
    } else {
      ladderEl.setAttribute("data-chi-pin", token);
      highlight(ladderEl, token);
    }
  }
}

/** Enter/Space on a focused rung does what a click does. The heads and arcs are
 *  real buttons, so the browser already gives them the same. */
function onKey(root, ev) {
  if (ev.key !== "Enter" && ev.key !== " " && ev.key !== "Spacebar") return;
  if (!closest(ev.target, ".chiasm-block .rung[data-chi-base]")) return;
  ev.preventDefault();
  ev.stopPropagation(); // the 3D pages bind Space/Enter globally in walk mode
  onClick(root, ev);
}

function onHover(root, ev, leaving) {
  const r = closest(ev.target, ".chiasm-block .rung[data-chi-base]");
  if (!r) return;
  const ladderEl = closest(r, ".ladder");
  if (!ladderEl || ladderEl.getAttribute("data-chi-pin")) return;
  highlight(ladderEl, leaving ? null : chiTokens(r)[0]);
}

/** Delegated handlers for a panel body. Safe to call after every re-render:
 *  the listeners are attached once per element, the options are refreshed. */
export function bind(rootEl, opts) {
  if (!rootEl || !rootEl.addEventListener) return;
  const first = !bound.has(rootEl);
  bound.set(rootEl, opts || {});
  if (!first) return;
  rootEl.addEventListener("click", ev => onClick(rootEl, ev));
  rootEl.addEventListener("keydown", ev => onKey(rootEl, ev));
  rootEl.addEventListener("mouseover", ev => onHover(rootEl, ev, false));
  rootEl.addEventListener("mouseout", ev => onHover(rootEl, ev, true));
  rootEl.addEventListener("focusin", ev => onHover(rootEl, ev, false));
  rootEl.addEventListener("focusout", ev => onHover(rootEl, ev, true));
}
